# Generated by Django 2.2.10 on 2020-02-23 17:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=10)),
                ('to_name', models.CharField(max_length=10, null=True)),
                ('mobile', models.CharField(max_length=10, null=True)),
                ('package_name', models.CharField(max_length=50, null=True)),
                ('package_type', models.CharField(max_length=20)),
                ('quantity', models.IntegerField(default=0)),
                ('weight', models.IntegerField(default=200)),
                ('address', models.CharField(max_length=500, null=True)),
                ('city', models.CharField(max_length=20)),
                ('order_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('delivered', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Details',
            },
        ),
    ]
